/**
 * Estados del turno según la máquina de estados (ART ME, TUR-007).
 * `SOLICITADO` (reserva temporal) → `CONFIRMADO` | `NO_CONFIRMADO`;
 * `CONFIRMADO` → `REPROGRAMADO` | `CANCELADO` | `ASISTIDO`.
 */
export enum EstadoTurno {
  SOLICITADO = 'SOLICITADO',
  CONFIRMADO = 'CONFIRMADO',
  NO_CONFIRMADO = 'NO_CONFIRMADO',
  REPROGRAMADO = 'REPROGRAMADO',
  CANCELADO = 'CANCELADO',
  ASISTIDO = 'ASISTIDO',
}
